SPECIES: GRCh38v35noalt
DOWNSAMPLE_MENIFEST: /home/hsher/projects/oligoCLIP/config/estimate_read_saturation/SLBP_bamUMI_PE.csv
SCRIPT_PATH: /home/hsher/scratch/eric_rbfox2_293t_snake/scripts/
GTF: /home/hsher/gencode_coords/gencode.v35.gtf.db
ANNOTATOR_SPECIES: GRCh38
GENOMEFA: /home/hsher/gencode_coords/GRCh38.p13.genome.fa
WORKDIR:  /home/hsher/scratch/SLBP_downsample/