fastq_menifest: /home/hsher/projects/oligoCLIP/config/fastq_csv/multiplex1.csv 

barcode: /projects/ps-yeolab5/hsher/barcodes.csv


ADAPTOR_PATH: /projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs
adaptor: InvRiL19

# Resources
CHROM_SIZES: /projects/ps-yeolab3/eboyle/resources/hg38.chrom.sizes
STAR_DIR: /projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/star_2_7_gencode29_sjdb
STAR_REP: /projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2


TOOL_PATH: /home/hsher/projects/oligoCLIP

umi_pattern: XXXXXNNNNN

WORKDIR: /home/hsher/scratch/ABC_reprocess/
QC_TOOLS_PATH: /home/hsher/projects/QC_tools